# Generated by Django 5.0.4 on 2025-08-30 15:08

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tipo_ingreso', models.CharField(choices=[('EF', 'Efectivo'), ('BB', 'BBVA'), ('S1', 'Santander 1'), ('S2', 'Santander 2'), ('HI', 'Hida'), ('ES', 'Esmeralda'), ('FA', 'Factory'), ('VA', 'Varios'), ('TA', 'Tarjetas')], max_length=2, verbose_name='Tipo de ingreso')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('cif_dni', models.CharField(max_length=50, unique=True, verbose_name='CIF/DNI')),
            ],
        ),
        migrations.CreateModel(
            name='FacturasIVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=100)),
                ('numero_factura', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagada', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='FacturaTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagada', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GastosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('gasto', models.CharField(max_length=255, verbose_name='Descripción del gasto')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
            ],
        ),
        migrations.CreateModel(
            name='GastosTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('gasto', models.CharField(max_length=255, verbose_name='Descripción del gasto')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PagosBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('concepto', models.CharField(max_length=255, verbose_name='Concepto')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField()),
                ('entregado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('principal', 'Principal'), ('raciones', 'Raciones'), ('bebida', 'Bebida'), ('postre', 'Postre')], max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ResumenVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('numero_pedidos', models.PositiveIntegerField(default=0)),
                ('total_pollos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_cachopos', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='PETTISSO', editable=False, max_length=100)),
                ('telefono_empresa', models.CharField(default='628932774', editable=False, max_length=20)),
                ('email_empresa', models.EmailField(default='agustintarrino@hotmail.com', editable=False, max_length=254)),
                ('numero_factura', models.CharField(max_length=20)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('fecha_entrega', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('nombre_emisor', models.CharField(default='Agustin Tarriño Castaño', editable=False, max_length=100)),
                ('direccion_emisor', models.CharField(default='Salvador Dali, 15, local 6-7, 2884, Mejorada del Campo, España', editable=False, max_length=255)),
                ('cif_nif_emisor', models.CharField(default='08983692F', editable=False, max_length=20)),
                ('total_neto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precio_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('total_neto', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.factura')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.menu')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.producto')),
            ],
        ),
        migrations.CreateModel(
            name='MenuProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.menu')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.producto')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='productos',
            field=models.ManyToManyField(through='base.MenuProducto', to='base.producto'),
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.producto')),
            ],
        ),
    ]
