# Generated by Django 5.1.2 on 2024-12-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tipo_ingreso', models.CharField(choices=[('EF', 'Efectivo'), ('BB', 'BBVA'), ('S1', 'Santander 1'), ('S2', 'Santander 2'), ('HI', 'Hida'), ('ES', 'Esmeralda'), ('VA', 'Varios')], max_length=2, verbose_name='Tipo de ingreso')),
            ],
        ),
    ]
