# Generated by Django 5.0.4 on 2025-08-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cif_nif_emisor',
            field=models.CharField(default='98765432B', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='factura',
            name='direccion_emisor',
            field=models.CharField(default='Avda. Ejemplo, Alcalá de Henares, España', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='factura',
            name='email_empresa',
            field=models.EmailField(default='ejemplo@hotmail.com', editable=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='factura',
            name='nombre_emisor',
            field=models.CharField(default='Alfredo Martínez Simón', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='factura',
            name='telefono_empresa',
            field=models.CharField(default='123456789', editable=False, max_length=20),
        ),
    ]
