# Generated by Django 5.1.2 on 2024-12-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_gastostienda_pagosbanco'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('gasto', models.CharField(max_length=255, verbose_name='Descripción del gasto')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
            ],
        ),
    ]
