# Generated by Django 5.1.2 on 2024-12-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_gastospersonales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('cif_dni', models.CharField(max_length=50, unique=True, verbose_name='CIF/DNI')),
            ],
        ),
    ]
