# Generated by Django 5.1.2 on 2024-12-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='tipo_ingreso',
            field=models.CharField(choices=[('EF', 'Efectivo'), ('BB', 'BBVA'), ('S1', 'Santander 1'), ('S2', 'Santander 2'), ('HI', 'Hida'), ('ES', 'Esmeralda'), ('VA', 'Varios'), ('TA', 'Tarjetas')], max_length=2, verbose_name='Tipo de ingreso'),
        ),
    ]
