# Generated by Django 5.1.2 on 2024-12-26 21:50

import base.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_venta_tipo_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='PETTISSO', editable=False, max_length=100)),
                ('telefono_empresa', models.CharField(default='628932774', editable=False, max_length=20)),
                ('email_empresa', models.EmailField(default='agustintarrino@hotmail.com', editable=False, max_length=254)),
                ('numero_factura', models.CharField(max_length=20)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('fecha_entrega', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('nombre_emisor', models.CharField(default='Agustin Tarriño Castaño', editable=False, max_length=100)),
                ('direccion_emisor', models.CharField(default='Salvador Dali, 15,local 6-7, 2884, Mejorada del Campo, España', editable=False, max_length=255)),
                ('cif_nif_emisor', models.CharField(default='08983692F', editable=False, max_length=20)),
                ('total_neto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precio_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.factura')),
            ],
        ),
    ]
