# Generated by Django 5.1.2 on 2024-12-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_factura_facturaproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaproducto',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total_iva',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total_neto',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facturaproducto',
            name='iva',
            field=models.DecimalField(decimal_places=3, editable=False, max_digits=5),
        ),
    ]
