# Generated by Django 5.1.2 on 2024-12-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_facturaproducto_total_alter_factura_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaproducto',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=10),
        ),
    ]
