# Generated by Django 5.1.2 on 2024-12-27 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_facturaproducto_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturaproducto',
            old_name='total',
            new_name='total_neto',
        ),
    ]
