# Generated by Django 5.1.2 on 2024-12-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_total_facturaproducto_total_neto'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaproducto',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=10),
        ),
    ]
