# Generated by Django 5.0.4 on 2024-12-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_factura_total_alter_factura_total_iva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='direccion_emisor',
            field=models.CharField(default='Salvador Dali, 15, local 6-7, 2884, Mejorada del Campo, España', editable=False, max_length=255),
        ),
    ]
