# Generated by Django 5.0.4 on 2025-01-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_facturasiva_facturatienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='tipo_ingreso',
            field=models.CharField(choices=[('EF', 'Efectivo'), ('BB', 'BBVA'), ('S1', 'Santander 1'), ('S2', 'Santander 2'), ('HI', 'Hida'), ('ES', 'Esmeralda'), ('FA', 'Factory'), ('VA', 'Varios'), ('TA', 'Tarjetas')], max_length=2, verbose_name='Tipo de ingreso'),
        ),
    ]
