# Generated by Django 5.0.4 on 2025-01-13 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_venta_tipo_ingreso'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Venta',
            new_name='Capital',
        ),
    ]
