# Generated by Django 5.0.4 on 2025-02-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturatienda',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
    ]
